#' Historic Stats Table
#'
#' @description Create a historic stats dataframe. NOTE: the inputs have to be of specific formats (mostly those generated by other functions as part of this package). If data has been saved in al_tablesernative formats, it is likely simpler to create the historic stats table manually.
#'
#' @param vars_assessment A list of contants. At least the following must be defined as list elements:
#' exam
#' exam_type
#' n_stages
#' academic_year
#' cohort
#' stages
#' n_items_incl
#' items_excl_comma_sep
#' test_angoff_corr_val
#' historic_stats_comment
#' @param l_tables A list of tables (dataframes). At least the following must be defined as list elements:
#' responseSummary
#' testDetails
#' reliability
#' gradeBoundaries
#'
#' @return Returns a formatted dataframe of historic stats
#' @export
#'
#' @examples historic_stats <- fn_historic_stats(vars_assessment = cnst, l_tables = tab)
#'
################################################################################
#'
fn_historic_stats <- function(vars_assessment = NULL,
                              l_tables = NULL) {
  if (is.null(vars_assessment) |
      is.null(l_tables)) {
    stop("One of the required variables for this function has not been specified.")
  } else{
    if (vars_assessment$exam_type %in% c("AMK")) {
      # For AMK, the reliability table must be reconstructed from the Stages A and Stages B tables
      l_tables$reliability <-
        cbind(l_tables$reliabilityStagesA, l_tables$reliabilityStagesB)
      # Need to manually set the Angoff Corr. to blank for AMK
      vars_assessment$test_angoff_corr_val <- ""
    }

    historic_stats <- tibble(
      Test = rep(vars_assessment$exam, vars_assessment$n_stages),
      AcYear = rep(vars_assessment$academic_year, vars_assessment$n_stages),
      Cohort = vars_assessment$cohort,
      Stage = vars_assessment$stages,
      Nstudents = as.numeric(l_tables$gradeDistribution["All", ]),
      Nitems = rep(vars_assessment$n_items_incl, vars_assessment$n_stages),
      ItemsExc = rep(vars_assessment$items_excl_comma_sep, vars_assessment$n_stages),
      Correct = as.numeric(l_tables$responseSummary["Percentage Correct", ]),
      Incorrect = as.numeric(l_tables$responseSummary["Percentage Incorrect", ]),
      DontKnow = as.numeric(l_tables$responseSummary["Percentage Don't Know", ]),
      Mean = as.numeric(l_tables$testDetails["Mean Score (%)", ]),
      SD = as.numeric(l_tables$testDetails["Std. Dev", ]),
      Min = as.numeric(l_tables$testDetails["Min Score (%)", ]),
      Max = as.numeric(l_tables$testDetails["Max Score (%)", ]),
      Alpha = as.numeric(l_tables$reliability["Cronbach's Alpha", ]),
      RelativeSEM = as.numeric(l_tables$reliability["Relative SEM", ]),
      Phi = as.numeric(l_tables$reliability["Phi Coefficient", ]),
      AbsoluteSEM = as.numeric(l_tables$reliability["Absolute SEM", ]),
      Borderline = as.numeric(l_tables$gradeBoundaries["Borderline", ]),
      Satisfactory = as.numeric(l_tables$gradeBoundaries["Satisfactory", ]),
      Excellent = as.numeric(l_tables$gradeBoundaries["Excellent", ]),
      AngoffCorrel = c(rep("", vars_assessment$n_stages - 1), vars_assessment$test_angoff_corr_val),
      Comments = vars_assessment$historic_stats_comment
    )

    return(historic_stats)
  }
}
