#' Historic Stats Table
#'
#' @description Create a historic stats dataframe. NOTE: the inputs have to be of specific formats (mostly those generated by other functions as part of this package). If data has been saved in alternative formats, it is likely simpler to create the historic stats table manually.
#'
#' @param listOfConstants A list of contants. At least the following must be defined as list elements:
#' assessment
#' nStages
#' academicYear
#' cohort
#' stages
#' nItemsIncl
#' itemsExclCommaSep
#' testAngoffCorrVal
#' historicStatsComment
#' @param listOfTables A list of tables (dataframes). At least the following must be defined as list elements:
#' responseSummary
#' testDetails
#' reliability
#' gradeBoundaries
#'
#' @return Returns a formatted dataframe of historic stats
#' @export
#'
#' @examples historicStats <- fnHistoricStats(listOfConstants = cnst, listOfTables = tab)
#'
################################################################################
#'
fnHistoricStats <- function(listOfConstants = NULL,
                            listOfTables = NULL) {
  if (is.null(listOfConstants) == TRUE |
      is.null(listOfTables) == TRUE) {
    stop("One of the required variables for this function has not been specified.")
  } else{
    # Rename incoming var for brevity and readability
    # Shorten list of constants var
    lC <- listOfConstants
    # Shorten list of tables var
    lT <- listOfTables

    historicStats <- list(
      "Test" = rep(lC$assessment, lC$nStages),
      "AcYear" = rep(lC$academicYear, lC$nStages),
      "Cohort" = lC$cohort,
      "Stage" = lC$stages,
      "Nstudents" = as.numeric(lT$gradeDistribution["All", ]),
      "Nitems" = rep(lC$nItemsIncl, lC$nStages),
      "ItemsExc" = rep(lC$itemsExclCommaSep, lC$nStages),
      "Correct" = as.numeric(lT$responseSummary["Percentage Correct", ]),
      "Incorrect" = as.numeric(lT$responseSummary["Percentage Incorrect", ]),
      "DontKnow" = as.numeric(lT$responseSummary["Percentage Don't Know", ]),
      "Mean" = as.numeric(lT$testDetails["Mean Score (%)", ]),
      "SD" = as.numeric(lT$testDetails["Std. Dev", ]),
      "Min" = as.numeric(lT$testDetails["Min Score (%)", ]),
      "Max" = as.numeric(lT$testDetails["Max Score (%)", ]),
      "Alpha" = as.numeric(lT$reliability["Cronbach's Alpha", ]),
      "RelativeSEM" = as.numeric(lT$reliability["Relative SEM", ]),
      "Phi" = as.numeric(lT$reliability["Phi Coefficient", ]),
      "AbsoluteSEM" = as.numeric(lT$reliability["Absolute SEM", ]),
      "Borderline" = as.numeric(lT$gradeBoundaries["Borderline", ]),
      "Satisfactory" = as.numeric(lT$gradeBoundaries["Satisfactory", ]),
      "Excellent" = as.numeric(lT$gradeBoundaries["Excellent", ]),
      # For AngoffCorrel, only want a value in the highest stage so fill the rest with empty cells
      "AngoffCorrel" = c(rep("", lC$nStages - 1), lC$testAngoffCorrVal),
      "Comments" = rep(lC$historicStatsComment, lC$nStages)
    )
    # Bind all vector elements of list to a df:
    historicStats <-
      suppressWarnings(data.frame(do.call(cbind, historicStats)))

    return(historicStats)
  }
}
