#' Plot multiple historic stats for multiple datasets
#'
#' @param data A dataframe OR vector of dataframes. For plotting multiple stats on a single dataframe of data, provide only a single dataframe (data = df1). For plotting multiple stats on multiple dataframes of data, provide a list of dataframes (plotData = list(df1, df2, df3), names(plotData = c("Data1", "Data2", "Data3"), data = plotData)). NOTE - when providing a list of dataframes, each dataframe must be names in the list (see example). The name of each df in the list will be appended to file names. In each provided dataframe (whether individual or in a list) there must be a unique column with the same name as each of the variables to plot (provided in 'listOfStats'). The chosen statistics will be plotted for each provided dataset
#' @param listOfStats A vector of the statistics to plot for each of the datasets in 'data'
#' @param savePlot A boolean (TRUE/FALSE, default TRUE) determines whether the plot will be saved. Useful for controlling overall save behaviour.
#' @param plotsFolder The root folder where images should be saved. Individual saved images are given unique names within that folder as part of this function
#'
#' @return ****
#' @export
#'
#' @examples
#' data1 <- list(statsAll, statsStagesA, statsStagesB)
#' names(.data1) <- c("All", "StagesA", "StagesB")
#' stats <- c("Mean", "Correct", "Incorrect", "DontKnow", "Phi")
#'
#' pltList <- list()
#' pltList <- append(pltList,
#'   fnPltHistoricStatsMultiple(
#'       data = data1,
#'       listOfStats = stats,
#'       savePlot = !any(lFiles$stopAllOutputs, lFiles$stopImageSaving),
#'       plotsFolder = lFiles$pathImages)
#'       )
#'
#' pltList2 <- list()
#' pltList2 <- append(pltList2,
#'   fnPltHistoricStatsMultiple(
#'       data = dfData,
#'       listOfStats = stats,
#'       savePlot = !any(lFiles$stopAllOutputs, lFiles$stopImageSaving),
#'       plotsFolder = lFiles$pathImages)
#'       )
#'
################################################################################
#'
fnPltHistoricStatsMultiple <-
  function(data = NULL,
           listOfStats = NULL,
           savePlot = NULL,
           plotsFolder = NULL) {
    if (is.null(data) == TRUE |
        is.null(listOfStats) == TRUE |
        is.null(plotsFolder) == TRUE) {
      stop("One of the required variables for this function has not been specified.")
    } else if (is.null(savePlot) == TRUE) {
      message(
        "fnPltHistoricStatsMultiple: The 'savePlot' variable has not been set. Defaulting to saving the plot."
      )
      savePlot <- TRUE
    }

    # Create a list to store the plots generated by this function
    listOfPlots <- list()

    if (is.data.frame(data)) {
      # Only a single df provided - create only a single set of plots
      # Not need for df to be named, the dataset name is not included in file naming
      message(
        "fnPltHistoricStatsMultiple: Only a single dataset has been provided. Creating a single set of historic stats plots only."
      )

      # Loop over all the stats to plot provided
      for (j in 1:length(listOfStats)) {
        # Save the current statistic being plotted
        loopStat <- listOfStats[j]
        # Variable for the current plot within the loop (for use when saving)
        # Saved to the list of plots also
        loopPlt <- listOfPlots[[glue("historic{loopStat}")]] <-
          fnPltHistoricStats(data, loopStat)

        fnPltSave(
          savePlot = savePlot,
          plot = loopPlt,
          filePath =  glue(
            '{plotsFolder}\\{fnTimestamp()}_Historic{loopStat}.jpg'
          )
        )
      }
    } else{
      # There is not a single df provided (must then be a list of dfs) - create historic stats plots across multiple datasets
      message(
        "fnPltHistoricStatsMultiple: Multiple datasets provided. Creating multiple sets of historic stats plots."
      )

      # Loop over all the dataframes provided
      for (i in 1:length(data)) {
        # Get the i'th element (df) from the list of data
        loopDf <- data.frame(data[i])
        # Remove all text before a '.' in col names (including the '.')
        # When taking the i'th element, the name of that element is added with a '.' before each col name. This is not desired
        colnames(loopDf) <- gsub(".*\\.", "", colnames(loopDf))
        # Loop over all the stats to plot provided
        for (j in 1:length(listOfStats)) {
          # Save the current statistic being plotted
          loopStat <- listOfStats[j]
          # Variable for the current plot within the loop (for use when saving)
          # Saved to the list of plots also
          loopPlt <-
            listOfPlots[[glue("historic{loopStat}{names(data[i])}")]] <-
            fnPltHistoricStats(loopDf, loopStat)

          fnPltSave(
            savePlot = savePlot,
            plot = loopPlt,
            filePath =  glue(
              '{plotsFolder}\\{fnTimestamp()}_Historic{loopStat}{names(data[i])}.jpg'
            )
          )
        }
      }
    }
    return(listOfPlots)
  } # END
