#' Plot multiple historic stats for multiple datasets
#'
#' @param listOfData A vector of dataframes. The chosen statistics will be plotted for each provided dataset
#' @param listOfStats A vector of the statistics to plot for each of the datasets in 'listOfData'
#' @param savePlot A boolean (TRUE/FALSE) determines whether the plot will be saved. Useful for controlling overall save behaviour
#' @param plotsFolder The root folder where images should be saved. Individual saved images are given unique names within that folder as part of this function
#'
#' @return ****
#' @export
#'
#' @examples ****
#'
################################################################################
#'
fnPltHistoricStatsMultiple <-
  function(listOfData,
           listOfStats,
           savePlot,
           plotsFolder) {
    # Create a list to store the plots generated by this function
    listOfPlots <- list()

    # Loop over all the dataframes provided
    for (i in 1:length(listOfData)) {
      # Get the i'th element (df) from the list of data
      loopDf <- data.frame(listOfData[i])
      # Remove all text before a '.' in col names (including the '.')
      # When taking the i'th element, the name of that element is added with a '.' before each col name. This is not desired
      colnames(loopDf) <- gsub(".*\\.", "", colnames(loopDf))
      # Loop over all the stats to plot provided
      for (j in 1:length(listOfStats)) {
        loopStat <- listOfStats[j]
        listOfPlots[[glue("historic{loopStat}{names(listOfData[i])}")]] <-
          fnPltHistoricStats(loopDf, loopStat)

        fnPltSave(
          savePlot = savePlot,
          plot = listOfPlots[[glue("historic{loopStat}{names(listOfData[i])}")]],
          filePath =  glue(
            '{plotsFolder}\\{fnTimestamp()}_Historic{loopStat}{names(listOfData[i])}.jpg'
          )
        )
      }
    }
    return(listOfPlots)
  } # END
