#' Title
#'
#' @param listOfCurrentPlots ***
#' @param listOfData ***
#' @param listOfStats ***
#'
#' @return ****
#' @export
#'
#' @examples ****
fnPltHistoricStatsMultiple <-
  function(listOfCurrentPlots,
           listOfData,
           listOfStats) {
    # Create a list to store the plots generated by this function
    listOfPlots <- list()

    # Loop over all the dataframes provided
    for (i in 1:length(listOfData)) {
      # Get the i'th element (df) from the list of data
      loopDf <- data.frame(listOfData[i])
      # Remove all text before a '.' in col names (including the '.')
      # When taking the i'th element, the name of that element is added with a '.' before each col name. This is not desired
      colnames(loopDf) <- gsub(".*\\.", "", colnames(loopDf))
      # Loop over all the stats to plot provided
      for (j in 1:length(listOfStats)) {
        loopStat <- listOfStats[j]
        listOfPlots[[glue("historic{loopStat}{names(listOfData[i])}")]] <-
          fnPltHistoricStats(loopDf, loopStat)

        fnPltSave(
          controls = lFileOutputs,
          plot = listOfPlots[[glue("historic{loopStat}{names(listOfData[i])}")]],
          dimensions = c(15, 15, "cm"),
          filePath =  glue(
            '{folderImages}\\{fnTimestamp()}_Historic{loopStat}{names(listOfData[i])}.jpg'
          )
        )
      }
    }
    # return(names(listOfPlots))
    listOfPlots <- append(listOfCurrentPlots, listOfPlots)
    return(listOfPlots)
    # END
  }


# TODO Fill in
